version: '3.8'
services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
      - 9200:9200
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana: 
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
      - 5601:5601
    depends_on:
      - elastic
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    networks:
      - elastic
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Web management UI
      - "5672:5672"    # RabbitMQ client connections
    environment:
      RABBITMQ_DEFAULT_USER: user  # Set default username
      RABBITMQ_DEFAULT_PASS: password  # Set default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data across restarts
    restart: always
    
networks:
  elastic:
    driver: bridge
    
volumes:
  elastic-data:
  rabbitmq_data:
    driver: local